export default [
  // "a0000" ~ "b0000"
  { init: "a2Qz4", until: "a4w00" },
  { init: "a4w00", until: "a7S00" },
  { init: "a7S00", until: "a9y00" },
  { init: "a9y00", until: "aCU00" },
  { init: "aCU00", until: "aF000" },
  { init: "aFK2m", until: "aIG00" },
  { init: "aIG00", until: "aLC00" },
  { init: "aLC00", until: "aO800" },
  { init: "aO800", until: "aR400" },
  { init: "aR400", until: "aU000" },
  { init: "aUJ00", until: "aXF00" },
  { init: "aXF00", until: "aaB00" },
  { init: "aaB00", until: "ad700" },
  { init: "ad700", until: "ag300" },
  { init: "ag300", until: "aj000" },
  { init: "ajJ00", until: "ame00" },
  { init: "ame00", until: "apz00" },
  { init: "apz00", until: "atK00" },
  { init: "atK00", until: "awf00" },
  { init: "awf00", until: "b0000" },

  // D000~a000
  { prefix: "fb", init: "Dbv0", until: "EA00" },
  { prefix: "fb", init: "EU31", until: "FK00" },
  { prefix: "fb", init: "Fe2y", until: "GU00" },
  { prefix: "fb", init: "Go3W", until: "He00" },
  { prefix: "fb", init: "Hy2o", until: "Io00" },
  { prefix: "fb", init: "J82y", until: "K000" },

  // fb/K000 ~ fb/a000
  { prefix: "fb", init: "Kbrw", until: "MHtY" },
  { prefix: "fb", init: "MHtY", until: "NxvA" },
  { prefix: "fb", init: "NxvA", until: "Pdwm" },
  { prefix: "fb", init: "Pdwm", until: "RJyO" },
  { prefix: "fb", init: "RJyO", until: "T000" },
  { prefix: "fb", init: "TbtJ", until: "Ut72" },
  { prefix: "fb", init: "Ut72", until: "WAKl" },
  { prefix: "fb", init: "WAKl", until: "XRYU" },
  { prefix: "fb", init: "XRYU", until: "YimD" },
  { prefix: "fb", init: "YimD", until: "a000" },
];
