export default [
  // "a0000" ~ "b0000"
  { init: "a2Qz4", until: "a4w00" },
  { init: "a4w00", until: "a7S00" },
  { init: "a7S00", until: "a9y00" },
  { init: "a9y00", until: "aCU00" },
  { init: "aCU00", until: "aF000" },
  { init: "aFK2m", until: "aIG00" },
  { init: "aIG00", until: "aLC00" },
  { init: "aLC00", until: "aO800" },
  { init: "aO800", until: "aR400" },
  { init: "aR400", until: "aU000" },
  { init: "aUJ00", until: "aXF00" },
  { init: "aXF00", until: "aaB00" },
  { init: "aaB00", until: "ad700" },
  { init: "ad700", until: "ag300" },
  { init: "ag300", until: "aj000" },
  { init: "ajJ00", until: "ame00" },
  { init: "ame00", until: "apz00" },
  { init: "apz00", until: "atK00" },
  { init: "atK00", until: "awf00" },
  { init: "awf00", until: "b0000" },

  // fb/D000~fb/K000
  // { prefix: "fb", init: "Dbv0", until: "EA00" },
  // { prefix: "fb", init: "EU31", until: "FK00" },
  // { prefix: "fb", init: "Fe2y", until: "GU00" },
  // { prefix: "fb", init: "Go3W", until: "He00" },
  // { prefix: "fb", init: "Hy2o", until: "Io00" },
  // { prefix: "fb", init: "J82y", until: "K000" },

  // fb/K000 ~ fb/a000
  { prefix: "fb", init: "LtEV", until: "MKmT" },
  { prefix: "fb", init: "MKmT", until: "MmKR" },
  { prefix: "fb", init: "MmKR", until: "NDsP" },
  { prefix: "fb", init: "NDsP", until: "NfQN" },
  { prefix: "fb", init: "NfQN", until: "O6yL" },
  { prefix: "fb", init: "O6yL", until: "OYWJ" },
  { prefix: "fb", init: "OYWJ", until: "P04H" },
  { prefix: "fb", init: "P04H", until: "PRcF" },
  { prefix: "fb", init: "PRcF", until: "PtAD" },
  { prefix: "fb", init: "PtAD", until: "QKiB" },
  { prefix: "fb", init: "QKiB", until: "QmG9" },
  { prefix: "fb", init: "QmG9", until: "RDo7" },
  { prefix: "fb", init: "RDo7", until: "RfM5" },
  { prefix: "fb", init: "RfM5", until: "S6u3" },
  { prefix: "fb", init: "S6u3", until: "SYS1" },
  { prefix: "fb", init: "SYS1", until: "T000" },
];
